Repository databrickslabs/pytester, pull requests merged in 2025-02, with the labels that each got.

#98 Refactor integration test
  tests/integration/fixtures/test_connect.py
Labels: internal

#106 Let `make_serving_endpoint` reference a valid model version
  README.md
  src/databricks/labs/pytester/fixtures/ml.py
  tests/unit/fixtures/test_ml.py
Labels: bug

#109 Set upper SDK limit to v1
  pyproject.toml
  src/databricks/labs/pytester/fixtures/ml.py
Labels: dependencies
